from turtle import *
windon = Screen()
control = Turtle()
control.speed(5000)
control.color("blue")
control.penup()
control.goto(-300, 0)
control.pendown()
control.begin_fill()
control.setheading(0)
for _ in range(2):
    control.forward(200)
    control.left(90)
    control.forward(50)
    control.left(90)
control.end_fill()
control.color("blue")
control.penup()
control.goto(-225, -50)
control.pendown()
control.begin_fill()
control.setheading(0)
for _ in range(2):
    control.forward(50)
    control.left(90)
    control.forward(150)
    control.left(90)
control.end_fill()
#chia
control.color("red")
control.penup()
control.goto(-50, 0)
control.pendown()
control.begin_fill()
control.setheading(0)
for _ in range(2):
    control.forward(200)
    control.left(90)
    control.forward(50)
    control.left(90)
control.end_fill()
control.begin_fill()
control.color("green")
control.penup()
control.goto(50, 55)
control.pendown()
control.circle(25)
control.left(45)
control.end_fill()
control.begin_fill()
control.color("green")
control.penup()
control.goto(65, -55)
control.pendown()
control.circle(25)
control.left(45)
control.end_fill()
#nhan
control.color("blue")
control.penup()
control.goto(300, -50)
control.pendown()
control.begin_fill()
control.setheading(0)
control.left(45)
for _ in range(2):
    control.forward(200)
    control.left(90)
    control.forward(50)
    control.left(90)
control.end_fill()
control.color("blue")
control.penup()
control.goto(280, 90)
control.pendown()
control.begin_fill()
control.setheading(0)
control.right(45)
for _ in range(2):
    control.forward(200)
    control.left(90)
    control.forward(50)
    control.left(90)
control.end_fill()
control.hideturtle()
windon.mainloop()