from tkinter import *
def add_to_list():
    name = name_entry.get()
    gender = gender_var.get()
    if name and gender:
        people_list.insert(END, f"{name}, {gender}")
        name_entry.delete(0, END)
        gender_var.set("M")
window = Tk()
window.title("People list")
name_label = Label(window, text="Nhập tên của bạn:")
name_label.grid(row=0, column=0, padx=10, pady=10)
name_entry = Entry(window)
name_entry.grid(row=0, column=1, padx=10, pady=10)
gender_label = Label(window, text="Chọn giới tính")
gender_label.grid(row=1, column=0, padx=10, pady=10)
gender_var = StringVar(window)
gender_var.set("M")
gender_menu = OptionMenu(window, gender_var, "M", "F")
gender_menu.grid(row=1, column=1, padx=10, pady=10)
people_list = Listbox(window)
people_list.grid(row=2, column=0, columnspan=2, padx=10, pady=10)
add_button = Button(window, text="Thêm vào danh sách", command=add_to_list)
add_button.grid(row=3, column=0, columnspan=2, padx=10, pady=10)
window.mainloop()